### ISSUE TITLE
Manual installation of packages required

### ISSUE THREAD

**Issue by alexbott** [XPRESSyourself/XPRESSpipe#1]
XPRESSpipe does not install xpressplot, numpydoc, and multiqc.

**Comment by j-berg** [comment]
Addressed in commit <a href='https://github.com/XPRESSyourself/XPRESSpipe/commit/2a674e8bb047d2e3285cee8ae4f0fa6149709335'>2a674e8</a>

It appears using a custom command class to handle installation was skipping the install_requires bit of the setup. Since these custom command classes are no longer being used, they were removed and xpresspipe appears to be installing missing pypi dependencies when running setup
