### ISSUE TITLE
xpresspipe won't pass the final installation check xpresspipe test

### ISSUE THREAD

**Issue by hollyjaro** [XPRESSyourself/XPRESSpipe#35]
Hello,

I tried to install the xpresspipe according to the installation tutorial. I did not encounter any warnings or bugs during installation but at the last step to check if everything is ok I am getting following:

Traceback (most recent call last):
  File "/nethome/hollyj2/miniconda3/envs/expresspipe-env/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

I tried to troubleshoot it by removing conda following the tutorial in FAQ section and do clean install with miniconda3 but I got the same result.
I would like to install and try to run the xpresspipe "locally" on our HPC.
Please see my command line output attached 
[xpresspipe_float_error.txt](https://github.com/XPRESSyourself/XPRESSpipe/files/4140483/xpresspipe_float_error.txt)

I would appreciate any hints how to solve it.
Thanks!

Jaro

**Comment by j-berg** [comment]
Hi Jaro,

Thanks for your interest in using XPRESSyourself, and thanks for all the details. From what I can tell, my suspicion is that this issue is arising in numpy, but maybe we can dig into this a little more. When I run `xpresspipe test`, I seem to be able to run everything smoothly, but could you activate your conda environment and send me what you get when you run `conda list`? Also, if your HPC environment SLURM, or something else. Sometimes, I would run into issues where default packages on the HPC would mess with the conda installations, so I would run `modules purge` to clear their installations from my environment.

This is the current version of numpy I am using that doesn't seem to raise any issues. The issue could also be related to Seaborn, so I've included my current version of that as well:
```
python                    3.7.4                h265db76_1  
conda                     4.7.12                   py37_0  
numpy                     1.17.2           py37hf9bf1b6_0  
numpy-base                1.17.2           py37h2f8d375_0  
seaborn                   0.9.0                    py37_0  
```

**Comment by hollyjaro** [comment]
Hi, thanks for the fast reply. I tried to purge the preloaded modules first and it didn't help. I checked the versions of numpy and seaborn. The seaborn was the same but the expresspipe installed numpy 1.18.1. After downgrade to 1.17.1 the problem was solved. Now I get the summary after I run the xpresspipe test command. It would help to restrict the installation to that version of numpy by default.

Bug solved!

Thank you!
Jaro

**Comment by j-berg** [comment]
Agreed, looks like 1.18 is new as of this month, so maybe there is some compatibility weirdness with the new version for whatever reason. I will restrict numpy to <=1.17 in the next release (probably this weekend or earlier) and if numpy>=1.18 works at some point in the future will remove the version restriction. 

Thanks!
