### ISSUE TITLE
Allow riboseq to handle paired end reads of both input and RPF libraries

### ISSUE THREAD

**Issue by jdreyf** [XPRESSyourself/XPRESSpipe#50]
@j-berg: It appears that paired end input libraries are accommodated with `peRNAseq`, but I don't see any mention of paired ends in the `riboseq` documentation at https://xpresspipe.readthedocs.io/en/latest/content/riboseq.html.

We have paired end input and RPF libraries, so we would like xpresspipe to handle this case.

Thanks for your continued help.

**Comment by j-berg** [comment]
Hi @jdreyf , sorry for the slow response. By default, we did not include PE capabilities with the `riboseq` module as more often then not, ribosome profiling is performed using SE sequencing due to the small size of the RPFs. If you have PE total RNA, I would process these samples separate from the RPF samples using the `peRNAseq` module, but I would have some hesitancy combining SE RPF and PE RNA reads in the same analysis, unless you were to include this distinction as a factor during differential expression analysis. I may be missing the point, but as far as I am aware, I have not seen any PE RPF library generation methods (or at least, none that are used widely).
